In [1]:
import numpy as np

In [2]:
l=[[1,1],[2,2],[3,3],[4,4]]

In [3]:
l

[[1, 1], [2, 2], [3, 3], [4, 4]]

In [4]:
np_arr=np.array(l)
np_arr

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [5]:
type(l),type(np_arr)

(list, numpy.ndarray)

In [7]:
li1=[1,2,3,4]
li2=[5,6,7,8]
li3=[9,10,11,12]
merged=np.array([li1,li2,li3])
merged

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
merged.shape

(3, 4)

In [10]:
merged[0][0]

1

In [11]:
merged[1][2]

7

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.random.rand(2,2)

array([[0.49896769, 0.17983374],
       [0.70456426, 0.67907669]])

In [19]:
n=np.arange(10,20)
n.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])