In [1]:
#Create a numPy ndarray object:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#Use a tuple to create a numPy array:
arrjim=np.array([1,2,3,4,5])
print(arrjim)

[1 2 3 4 5]


In [4]:
#Dimensions in Array: 0-D Array
arr1=np.array(42)
print(arr1)

42


In [6]:
#1-D Arrays:
arr2=np.array([1,2,3,4,5])
print(arr2)

[1 2 3 4 5]


In [9]:
#2-D Array
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [11]:
#3D Array:
arr4=np.array([[[7,8,9],[10,11,12],[13,14,15]]])
print(arr4)

[[[ 7  8  9]
  [10 11 12]
  [13 14 15]]]


In [13]:
#Check the number of Dimensions: with ndim attribute
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
#Higher Dimensional Arrays with ndim arguments
#Acces 1-D array:
arr5=np.array([[1,2,3,4],[5,6,7,8]])
print(arr5)
print('number of dimensions: ',arr5.ndim)

[[1 2 3 4]
 [5 6 7 8]]
number of dimensions:  2


In [20]:
#NumPy Array Indexing:
#Frst element:
arr6=np.array([1,2,3,4,5])
print(arr6[2])

3


In [21]:
#Third and Fourth elements from the followning arrays and add them:
arr8=np.array([1,2,3,4])
print(arr8[2]+arr8[3])

7


In [25]:
#Access 2-D Arrays:
arr9=np.array([[1,2,3,4],[5,6,7,8]])
print("Second element on first row: ",arr9[1,3])

Second element on first row:  8


In [26]:
#Access 3D Array:
#Access the lelement of the second array of the first array
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr1[0,1,2])

6


In [27]:
#NumPy Array Sclicing
#Slicing means taking elements from one given index to another given index
#[start:end]
#Sclicing elements from index 1 to index 5 from the following array:
arr12=np.array([1,2,3,4,5,6,7])
print(arr12[1:5])

[2 3 4 5]


In [28]:
#Slice elements from index 4 to the end of the array
arr13=np.array([1,2,3,4,5,6,7])
print(arr13[4:])

[5 6 7]


In [29]:
#Slice elements from index begeining to 4
arr14=np.array([1,2,3,4,5,6,7])
print(arr14[:4])

[1 2 3 4]


In [30]:
#Slice 2D Arrays:
#From the second element, slice elelments from index 1 to index 4
arr15=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr15[1,1:4])

[ 9 10 11]


In [31]:
#From both elements return index 2:
arr16=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr16[0:2,2])

[3 8]


In [34]:
#NumPy Array copy vs view
#copy
arr19=np.array([1,2,3,4,5])
x=arr19.copy()
arr19[0]=42
#x=arr19.copy()
print(arr19)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [35]:
#View
arr20=np.array([1,2,3,4,5,6])
x=arr20.view()
arr20[0]=77
print(arr20)
print(x)

[77  2  3  4  5  6]
[77  2  3  4  5  6]


In [39]:
#Numpy Array Shape:
#Print the shape of a 2D aArray:
arr21=np.array([[1,2,3,4],[5,6,7,8]])
print(arr21.shape)

(2, 4)


In [40]:
#Numpy Array Shape:
#Print the shape of a 2D aArray:
arr21=np.array([[1,2,3,4],[5,6,7,8]])
print(arr21.shape)

(2, 4)


In [43]:
#Numpy Array Shape:
#Print the shape of a 2D aArray:
arr22=np.array([1,2,3,4,5,6,7,8])
newarr=arr22.reshape(2,4)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [45]:
#Numpy Array Shape:
#Print the shape of a 3D aArray:
arr23=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr1=arr23.reshape(2,3,2)
print(newarr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [46]:
#NumPy Array Iterating:
arr24=np.array([1,2,3])
for x in arr24:
    print(x)

1
2
3


In [47]:
#Iterating 2D Arrays:
arr25=np.array([[1,2,3],[4,5,6]])
for x in arr25:
    print(x)

[1 2 3]
[4 5 6]


In [48]:
#Iterating 3D Arrays:
arr26=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in arr26:
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
#NumPy Joining Array:
#Join two arrays:
arr27=np.array([1,2,3])
arr28=np.array([4,5,6])
arr29=np.concatenate((arr27,arr28))
print(arr29)

[1 2 3 4 5 6]


In [51]:
#Numpy spliting array:
#split the array in 3 parts:
arr33=np.array([1,2,3,4,5,6])
newarr4=np.array_split(arr33,3)
print(newarr4)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [53]:
#NumPy Searching Arrays:
#Find the indexes where the value is 4:
arr35=np.array([1,2,3,4,5,6,7])
x=np.where(arr35==4)
print(x)

(array([3], dtype=int64),)


In [55]:
#NumPy Searching Arrays:
#Find the indexes where the values are even:
arr36=np.array([1,2,3,4,5,6,7,8,9,10])
x1=np.where(arr36%2==0)
print(x1)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [56]:
#NumPy Searching Arrays:
#Find the indexes where the values are odd:
arr37=np.array([1,2,3,4,5,6,7,8,9,10])
x2=np.where(arr36%2==1)
print(x2)

(array([0, 2, 4, 6, 8], dtype=int64),)


In [57]:
#NumPy Sorting Arrays: with sort() function
arr38=np.array([9,8,7,6,5,4,3,2])
print(np.sort(arr38))

[2 3 4 5 6 7 8 9]


In [58]:
#NumPy Sorting Arrays: with sort() function
arr38=np.array([9,8,7,6,5,4,3,2])
x3=np.sort(arr38)
print(x3)

[2 3 4 5 6 7 8 9]
